apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamo-pvc
  namespace: dynamo-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: azurelustre-static
