apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller.yaml
- prometheus.yaml
images:
- name: ghcr.io/ai-runway/airunway/controller
  newName: ghcr.io/kaito-project/airunway/controller
  newTag: 0.7.0
