apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airunway-dynamo-provider-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia/ai-dynamo
    chart: dynamo-crds
    targetRevision: 0.9.1
    helm:
      releaseName: dynamo-crds
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airunway-dynamo-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia/ai-dynamo
    chart: dynamo-platform
    targetRevision: 1.0.1
    helm:
      releaseName: dynamo-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: dynamo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
