apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-inference-extension
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    name: gateway-api-inference-extension
    repoURL: https://github.com/kubernetes-sigs/gateway-api-inference-extension.git
    targetRevision: v1.5.0
    path: config/crd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
