apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - name: gateway-api
      repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.5.1
      path: config/crd
    - name: gaie
      repoURL: https://github.com/kubernetes-sigs/gateway-api-inference-extension.git
      targetRevision: v1.5.0
      path: config/crd
    - name: bbr
      repoURL: registry.k8s.io/gateway-api-inference-extension/charts
      chart: body-based-routing
      targetRevision: v1.5.0
      helm:
        releaseName: body-based-router
        namespace: istio-system
        valuesObject:
          provider:
            name: istio
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true